name: Automacao de Precos Diaria

# Força para o NODE JS 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

# Horario de execução e habilitar execução manual
on:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 19 * * *'

  workflow_dispatch: 

jobs:
  executar-robo:

    # Tipo de computador usar
    runs-on: ubuntu-latest
    
    # Habilitar permissão ao robô para modificar ficheiros e guardar no GitHub
    permissions:
      contents: write

    steps:

      # 1. Fazer o download do código para o computador do GitHub
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      # 2. Instalar o Python e a ferramenta "uv"
      - name: Instalar o Python e o UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true

      # 3. UV para instalar o pandas, requests, bs4, etc através do pyproject.toml
      - name: Instalar bibliotecas
        run: uv sync

      # 4. Executar o script Python
      - name: Rodar a automação e enviar e-mail
        env:
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          SENHA_APP_GMAIL: ${{ secrets.SENHA_APP_GMAIL }}
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
        run: uv run automacao.py

      # 5. Salvar o CSV atualizado no repositório
      - name: Guardar o histórico (CSV) no GitHub
        run: |
          git config --global user.name "Robô do GitHub"
          git config --global user.email "actions@github.com"
          git add dados/historico_precos.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Atualiza histórico de preços diário [Automático]"
          git push